apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "losant-device.fullname" . }}-gea-data
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "losant-device.labels" . | nindent 4 }}
    app.kubernetes.io/component: gea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gea.storage.size }}
  {{- if .Values.gea.storage.storageClassName }}
  storageClassName: {{ .Values.gea.storage.storageClassName }}
  {{- end }}
