{{- if not .Values.gea.credentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "losant-device.fullname" . }}-gea-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "losant-device.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEVICE_ID: {{ .Values.gea.credentials.secretValues.deviceID | quote }}
  ACCESS_KEY: {{ .Values.gea.credentials.secretValues.accessKey | quote }}
  ACCESS_SECRET: {{ .Values.gea.credentials.secretValues.accessSecret | quote }}
{{- end }}
