---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - losant.io
  resources:
  - losantsyncs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - losant.io
  resources:
  - losantsyncs/status
  - ranchersessions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - losant.io
  resources:
  - ranchersessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
