apiVersion: v1
kind: ServiceAccount
metadata:
  name: losant-device-controller
  namespace: losant-system
  labels:
    app.kubernetes.io/name: losant-device-controller
    app.kubernetes.io/component: controller
