apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: losant-gea-data
  namespace: losant-system
  labels:
    app: losant-gea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
