apiVersion: v2
name: losant-device
description: Kubernetes operator that monitors cluster health and reports metrics to the Losant IoT platform
type: application
version: 0.1.0
appVersion: v0.1.0-alpha.13
keywords:
  - losant
  - iot
  - kubernetes
  - operator
  - monitoring
home: https://github.com/mak3r/losant-device
sources:
  - https://github.com/mak3r/losant-device
maintainers:
  - name: Mark Abrams
    email: mabrams@helpguest.com
